
title: lordnet-userbot
email: lordgrief176@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  lordnet-userbot лучший юзербот для телеграм.
  Удобное написание модулей, высокая скорость работы,
  большое комьюнити.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "docs.lordnet.ml"
url: "https://docs.lordnet.ml" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lordcodes1
github_username:  LORD-ME-CODE

remote_theme: just-the-docs/just-the-docs

# Just-the-docs
permalink: pretty

color_scheme: dark

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false


# FOOTER
footer_content: "Copyright &copy; 2022 lordnet. Distributed by an <a href=\"https://github.com/LORD-ME-CODE/lordnet-userbot/tree/main/LICENSE\">GNU V3.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: false

search_enabled: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
