
title: lordnet-userbot
email: lordgrief176@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
domain: "docs.lordnet.ml"
url: "https://docs.lordnet.ml" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: lordcodes1
github_username:  LORD-ME-CODE

remote_theme: just-the-docs/just-the-docs

# Just-the-docs
color_scheme: dark

# FOOTER
footer_content: "Copyright &copy; 2022 lordnet. Distributed by an <a href=\"https://github.com/LORD-ME-CODE/lordnet-userbot/tree/main/LICENSE\">GNU V3.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

gh_edit_link: false

# HEADER
heading_anchors: true
search_enabled: true
